version: "3"

services:  
  calculator-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: "true"
      REACT_APP_AUTHORIGIN: "http://localhost"
      ENV: "development"
      PORT: "3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules