FROM node:current-alpine

# COPY ["package.json", "package-lock.json", "/usr/src/"]
COPY ["package.json", "/usr/src/"]

WORKDIR /usr/src

RUN npm install --silent

RUN npm audit fix -audit-level=none

RUN npm install nodemon

COPY [".", "/usr/src/"]

CMD ["npm", "run", "dev"]
